name: Evaluate Assignment

on:
  push:
    branches:
      - Emp-*-*-python

jobs:
  test-and-evaluate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create README if not exists
      run: |
        if [ ! -f README.md ]; then echo -e "# Assignment Scores\n\n## Scores\n\n" > README.md; fi

    - name: Run tests
      id: run-tests
      continue-on-error: true
      run: pytest --junitxml=test-results.xml

    - name: Evaluate and update README
      run: python evaluate.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add README.md
        git commit -m "Update scores in README.md"
        git push
